flag=-Xlint:unchecked
# practica 1
1c: build1c run1c
1l: build1l run1l
build1c:
	clear
	javac practica1/CircularQ/TestCQ_ite.java #$(flag)
run1c:
	java practica1.CircularQ.TestCQ_ite
build1l:
	clear
	javac practica1/LinkedQ/TestLQ_ite.java #$(flag)
run1l:
	java practica1.LinkedQ.TestLQ_ite
