flag=-Xlint:unchecked
# test
test:
	javac Test.java #$(flag)
	java Test

# practica 1
1c:
	javac practica1/CircularQ/TestCQ_ite.java
	java practica1.CircularQ.TestCQ_ite
1l:
	javac practica1/LinkedQ/TestLQ_ite.java
	java practica1.LinkedQ.TestLQ_ite
1p:
	javac practica1/Protocol/Test.java
	java practica1.Protocol.Test

2:
	javac practica2/P0CZ/TestSum.java
	java practica2.P0CZ.TestSum
2m:
	javac practica2/P0CZ/Monitor/TestSumCZ.java
	java practica2.P0CZ.Monitor.TestSumCZ
