flag=-Xlint:unchecked
# test
test:
	javac Test.java #$(flag)
	java Test
# practica 1
1c:
	javac practica1/CircularQ/TestCQ_ite.java #$(flag)
	java practica1.CircularQ.TestCQ_ite
1l:
	javac practica1/LinkedQ/TestLQ_ite.java #$(flag)
	java practica1.LinkedQ.TestLQ_ite
1p:
	javac practica1/Protocol/Test.java #$(flag)
	java practica1.Protocol.Test
